CONFIG_I2C=y
CONFIG_INPUT_IQS9151=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_NON_LIPO_MAX_MV=3000
CONFIG_ZMK_NON_LIPO_MIN_MV=2000
CONFIG_ZMK_NON_LIPO_LOW_MV=2000

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n